# Generated by Django 5.1.2 on 2024-10-29 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bus_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seat_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus', to='api.seatplan'),
        ),
    ]
