# Generated by Django 5.1.2 on 2024-10-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_bus_bookings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
    ]
