# Generated by Django 5.1.2 on 2024-10-29 23:00

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_route_unique_together'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bus',
            managers=[
                ('read_only_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='route',
            managers=[
                ('route_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='scheduled_date',
            field=models.DateField(auto_now=True),
        ),
    ]
