# Generated by Django 5.1.2 on 2024-10-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stop_alter_route_managers_rename_source_route_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routestops',
            unique_together={('route', 'stop')},
        ),
    ]
