# Generated by Django 5.1.2 on 2024-10-30 01:27

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_routestops_unique_together'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='route',
            managers=[
                ('route_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='bus',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='thrusday',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='wednesday',
        ),
        migrations.AlterUniqueTogether(
            name='routestops',
            unique_together={('route', 'stop', 'stop_sequence')},
        ),
    ]
