# Generated by Django 5.1.2 on 2024-10-31 03:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_route_managers_remove_bus_friday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatplan',
            name='name',
            field=models.CharField(default='SeatPlan', max_length=50),
        ),
        migrations.AlterField(
            model_name='bus',
            name='scheduled_date',
            field=models.DateField(default=datetime.date(2024, 10, 31)),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seat_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus', to='api.seatplan'),
        ),
    ]
