# Generated by Django 5.1.2 on 2024-10-31 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_seatplan_name_alter_bus_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestops',
            name='travel_time',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
